version: '3'
services:

  server:
    image: "rancher/k3s:v1.29.1-rc2-k3s2"
    command: server --tls-san server
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_TOKEN=rrgjqqgNhZme0oMOBj6TNDJ95ig2OKtOs1uY
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    - helm-node:/output
    ports:
    - 6443:6443  # Kubernetes API Server
    - 2080:80      # Ingress controller port 80
    - 2443:443    # Ingress controller port 443
    - 2223:30200
  agent:
    image: "rancher/k3s:v1.29.1-rc2-k3s2"
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=rrgjqqgNhZme0oMOBj6TNDJ95ig2OKtOs1uY

  ubuntu:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - helm-node:/output
    cap_add:
      - AUDIT_WRITE
    ports:
      - "2222:22"  # Map SSH to a non-standard port to avoid conflicts
    depends_on:
      - server

volumes:
  k3s-server:
  helm-node: